### ISSUE TITLE
ACF location rule "Has child"

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fuxt-backend#56]
It would be really useful to have an ACF location rule that allowed us to add a field group to a page that has NO children (or the opposite, only pages that have children)

**Comment by drewbaker** [comment]
Obviously needs to work with custom post types like our other custom rules

**Comment by drewbaker** [comment]
I see code for this, but doesn't show up for CPTs that is for sure

**Comment by rsm0128** [comment]
@drewbaker 
While developing the `Has Child`, we discussed using `Post has children` for CPTs as well. Right now the rule also works for the CPTs as well.
![image](https://github.com/funkhaus/fuxt-backend/assets/45686588/e185c53f-644c-4641-aac4-e4894c0fa23a)

To avoid confusion, I think it's better to add just one global location rule `Has Child` instead of having separate rules by post types (like `Post has children`, `Page has children`)
